# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 57be53af5bdd6ead9921817c1b11bdffc31660523de789838168e428812a693503cecf97e75e42f4fa76c9d9447adb5b8a4ccb044093a551075a07131d74d689

test:
  secret_key_base: 33e61f08b85326120fbaf5b36647349ecf73b7b71a3f7f7b9665ea0b390802dbbf86d398061f4de532423911fafe15628a7bb5f68a97ee39c5195a6305c3d53b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
